### ISSUE TITLE
Add T3-COO next to nightfall

### ISSUE THREAD

**Issue by hmsaleem** [TrackerNetwork/DestinyStatus#25]
Since the weekly was removed, there is empty space. T3 follows a strict cycle and can be coded in if not available through the API

**Comment by iBotPeaches** [comment]
True, but our codebase currently has no idea of weeklys in terms of that. It knows the last weekly and upcoming weekly (along with last/next daily). This allows us to check if completed events fall between those dates (therefore happened in this weekly/daily)

However, these are just dates. There is nothing that says "I'm the ___ weekly since the start", so there is no easy way to do a mod 3 to toggle on the T3 bosses. So this would require some changes to get this done.

**Comment by iBotPeaches** [comment]
Closing in preps for Destiny 2. Sorry I never got this implemented in the Destiny 1 version of DestinyStatus
