### ISSUE TITLE
Maximum Grimoire Score is incorrect

### ISSUE THREAD

**Issue by crstauf** [TrackerNetwork/DestinyStatus#34]
[Site](http://destinystatus.com/psn/dployed/grimoire) reports that 4890 is the max grimoire score, when it's actually 4895 (see attached screenshot).

![cbtujatumaawkhu](https://cloud.githubusercontent.com/assets/4573033/13066807/a744b6a6-d437-11e5-9472-090bbca74064.jpg)

**Comment by iBotPeaches** [comment]
This is a bug, but quite difficult to fix. In terms of the data available to us in the API, if we iterate through every grimoire card and count up the "point" values in each card we arrive at 4890.

There is two problems with that.
1. That value is not the same for Xbox users.
2. That value is wrong for the max for PSN users.

The problem stems from a grimoire card that gives points, but the API does not say such card gives points. There also additionally was problems in the past with grimoire cards saying they award points, but not actually giving them (A certain dead ghost).

Now the old system used to deal with both of these problems.

```
    /**
     * @var array
     */
    protected $nostats = [
        #'609012' // Doubles
        #'103094', // Dead Ghosts
    ];

    /**
     * @var array
     */
    protected $patchTotalPoints = [
        /*
        '107020' => 15, // Ghost Fragment: Rasputin 3
        '107030' => 10, // Ghost Fragment: Rasputin 2
        '201158' => 10, // Ghost Fragment: Hive 4
        '502130' => 5, // The Wakening
        '601071' => 15, // Omnigul, Will of Crota
        '601074' => 15, // Ir Yût, the Deathsinger
        '601145' => 5, // Will of Crota
        '603035' => 5, // Crota's End
        '603040' => 5, // Ascendant Sword
        '609130' => 5, // The Cauldron
        '609170' => 5, // Pantheon
        '609180' => 5, // Skyshock
        '692030' => 15, // Might of Crota
        */
    ];
```

As you can see they are commented out now, because the cards that didn't report proper points were fixed and the cards that didn't award points were fixed. We simply have to find the buggy grimoire and patch for this.

**Comment by bladefist** [comment]
@iBotPeaches Destiny Tracker is the same way, I think this is a confirmed bug in the api.   I reported this a long time ago and they confirmed it was off.

**Comment by iBotPeaches** [comment]
The massive comment I wrote here - https://github.com/TrackerNetwork/DestinyStatus/issues/34#issuecomment-184673099

Is the best course of action for this. If we learn what cards are unlocked and not rewarding points or discover what cards say they earn no points, but do then we can perfect this. We trust the Bungie API and in this case its wrong.

Thanks for report and sorry for delay.
