### ISSUE TITLE
Should "Activities Cleared" count patrol?

### ISSUE THREAD

**Issue by bradchoate** [TrackerNetwork/DestinyStatus#56]
As far as I know, patrol missions can't be cleared... I have cleared all the story missions I've started, but DS shows 19/25 as cleared. Or is this one of those things that can't be helped since Bungie counts them that way?

**Comment by iBotPeaches** [comment]
Interesting. This is just a raw value from the API. If there is an easy way to get total patrols, we probably can blanket remove those values from the totals to get a more correct representation of activities cleared. I will look into it.

**Comment by iBotPeaches** [comment]
We might be able to do this with some math. We can leverage the `activityStats` endpoint, which returns based on `activityHash`, all activities completed and the associated stats. Activities individually, we don't really care about for this.

We care about patrols, which all seem to have `activityTypeHash` of `3497767639`.

```
  'activityTypeHash' => 3497767639,
  'identifier' => 'ACTIVITY_TYPE_EXPLORE',
  'activityTypeName' => 'Patrol',
```

Except, after writing the code to do this. The `activityCompletions` count for all Patrols is `0`. So that won't work.

I've learned that both activities in Social spaces and Patrol count towards this value, but neither have the aggregate stats to remove later on. It doesn't seem this is possible to do with the current API Bungie has. Sorry.
